apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opsimate.configMapName" . }}
  labels:
    {{- include "opsimate.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- .Values.config.configYml | nindent 4 }}