{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsimate.secretName" . }}
  labels:
    {{- include "opsimate.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded API token
  API_TOKEN: {{ .Values.secrets.apiToken | b64enc | quote }}
{{- end }}