apiVersion: v2
name: opsimate
description: OpsiMate - A Helm chart for deploying the OpsiMate application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Sai
    email: burra.sa@northeastern.edu
