name: Validate PR Title

# todo: disabled until we will publish the package as an open source
#on:
#  pull_request:
#    branches: [ main ]
#    types: [opened, edited, reopened, synchronize]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title with regex
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const regex = /^(Feature|Task|Bugfix):\s.+/;

            if (!regex.test(title)) {
              core.setFailed(`❌ Invalid PR title: "${title}".\nTitle must start with 'Feature:', 'Task:', or 'Bugfix:' followed by a space and description.`);
            } else {
              console.log(`✅ Valid PR title: "${title}"`);
            }
